fullnameOverride: ""
nameOverride: ""
replicaCount: 1

image:
  repository: ollama/ollama
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 11434

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 50Gi
  retain: true

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
commandOverride:
  enabled: false
  command: /bin/true
  args: []
